version: '3.8'

include:
  - path:
    - ../docker-compose.yml
    - compose.generate.override.yml

services:
  generator:
    build:
      context: .
      dockerfile: generate.Dockerfile 
    volumes:
      - schema_data:/app/schema:ro
      - ./src/api:/app/src/api
    depends_on:
      backend:
        condition: service_completed_successfully
