version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      backend:
        condition: service_started

  backend:
    build: backend
    env_file:
      - .env
    environment:
      BASE_URL: ''
      MONGO_HOST: db
      MONGO_PORT: 27017
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:6.0
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    

volumes:
  mongodb_data:
