version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - 8000:80
    depends_on:
      backend:
        condition: service_started

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      BASE_URL: ""
      MONGO_HOST: db
      MONGO_PORT: 27017
    depends_on:
      db:
        condition: service_started

  db:
    image: mongo:6.0
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

volumes:
  mongodb_data:
