version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_started

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

volumes:
  mongodb_data:
